global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proposta'
    scrape_interval: 5s
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['proposals:8081']